### ISSUE TITLE
bug: modal font family does not work at firefox

### ISSUE THREAD

**Issue by hyesungoh** [effective-tech-interview/effective-tech-interview-client#46]
## 📣 이슈 내용

안녕하세요 ~ 서비스 재밌게 보고 있습니다 !! 👍 👍 

버그인 것 같은 부분을 찾아 제보 드립니다 ~

## ✏️ 상세 설명

![스크린샷 2023-03-24 오후 1 58 57](https://user-images.githubusercontent.com/26461307/227428592-0efdef38-9c23-474f-a138-3c040d60c6f2.png)

> 환경은 macOS, Firefox 112 입니다 !

**Comment by L2HYUNN** [comment]
헉 이런 버그가 있었군요..!
아직 부분 부분 문제있는 부분이 있어서 QA 진행하고 있어요!!
얼른 해결해보겠습니다 👀 감사합니다~!

**Comment by L2HYUNN** [comment]
@hyesungoh 
이슈 해결했습니다~! `safari`에서도 동일 이슈가 있더라고요.
덕분에 초기에 발견할 수 있었어요~! 

감사합니다 👍👍
